### ISSUE TITLE
M呢?

### ISSUE THREAD

**Issue by VictoryWangV** [limedroid/XDroidMvp#1]
大哥,既然是MVP,为嘛我只看到了V和P,M是哪个?如果我有一些操作需要访问数据库或网络,应该在哪做?望指教,谢谢

**Comment by limedroid** [comment]
您好，M一般是通用的，比如说缓存和网络api请求，跟单独的P关系不大，也不是每个P都需要的。可以在P中调用M，您所谓的M其实框架中已有部分实现，如net、cache。 欢迎加入QQ群：153569290  有问题大家共同讨论。谢谢  @VictoryWangV
