### ISSUE TITLE
adapter更新数据的小bug

### ISSUE THREAD

**Issue by registernet** [limedroid/XDroidMvp#2]
XListAdapter里面有个小bug,
public void setData(T[] data) {
        if (data != null && data.length > 0) {
            setData(Arrays.asList(data));
        }
    }
这个方法里面,假设你有一个列表,允许用户删除元素,当删除完最后一个时,列表不会更新,并且,如果事件处理的位置没有非空判断的话,很可能还会空指针或者index越界.

**Comment by limedroid** [comment]
您好 ， 我实在没明白您的意思，删除元素调用remove方法，在使用过程中也没遇到您所描述的问题。您能加入交流群和我详细说说吗？谢谢！
