### ISSUE TITLE
DiskCache put时一直过期BUG

### ISSUE THREAD

**Issue by dengciping0716** [limedroid/XDroidMvp#21]
问题出在正则表达式上
    static String REGEX = "=====createTime\\{(\\d{1,})\\}expireMills\\{(\\d{1,})\\}";
改为可以解决
    static String REGEX = "=====createTime\\{(\\d{1,})\\}expireMills\\{(-?\\d{1,})\\}";

原因在 NO_CACHE = -1L;是负数。前面的正则不能匹配负数。

**Comment by limedroid** [comment]
fixed
