### ISSUE TITLE
导入module时出现了警告，mvp这个模块没有被当做库编译

### ISSUE THREAD

**Issue by TakanashiHitomi** [limedroid/XDroidMvp#8]
刚刚按照readme里面的步骤将mvp模块导入了，并且添加了依赖，但是在build的时候出现了如下警告：
>Warning:Unable to find module with Gradle path ':mvp' (needed by module 'app'.)
Linking to library 'mvp-unspecified' instead.

现在mvp模块还没有办法使用，请问如何操作？谢谢！

**Comment by TakanashiHitomi** [comment]
这是在引入我的app时出现的，直接build下载好的项目则没有这个问题

**Comment by limedroid** [comment]
您是通过import module的方式吗？请确认您的`setting.gradle`中含有
```
include ':app', ':mvp'
```
强烈建议您加入XDroid交流群。 @TakanashiHitomi

**Comment by TakanashiHitomi** [comment]
是的，是import进来的，并且我已经申请了加入群，详细gradle信息我稍后会贴上来

**Comment by TakanashiHitomi** [comment]
重新导入并且改了个名字就好了。。。有点莫名其妙。。。

**Comment by initialjie** [comment]
一样，改名字就好了，估计是AS的BUG，蛋疼
