### ISSUE TITLE
导入后编译错误

### ISSUE THREAD

**Issue by JamesLiAndroid** [limedroid/XDroidMvp#9]
Error:Execution failed for task ':mvp:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
/home/jyj-lsy/workspace/XDroidMvp/mvp/src/main/java/cn/droidlover/xdroidmvp/net/XApi.java
Error:(103, 17) error: cannot find symbol class LogInterceptor
Error:(103, 53) error: cannot find symbol class LogInterceptor

**Comment by limedroid** [comment]
您好 ，LogInterceptor 这个类我忘记提交了，晚上回家提交，谢谢您的反馈。 @JamesLiAndroid

**Comment by zonectmac** [comment]
同上

**Comment by limedroid** [comment]
已提交   @JamesLiAndroid @zonectmac
